### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by JunkMyFunk** [danielbayley/atom-custom-app-icon#2] opened 2016-08-09 08:57 UTC
I installed this and put the .icns file from [here](https://atom.io/themes/atom-material-ui) into `/Users/Me/.atom/`, named it Atom.icns but I don't see any change to my icon, even after a couple of restarts?

`Atom 1.9.6`
`OSX 10.11.6`

**Comment by danielbayley** [comment] 2016-09-23 01:40
@JunkMyFunk I just pushed a fix; it should work now… let me know, cheers!

**Comment by ndobson** [comment] 2016-10-14 16:24
Yeah doesn't seem to work for me either, running MacOS Sierra fyi

Also, i can't make heads or tails out of that zsh script but it's placing a file name "*" in my /Applications/Atom.app/Contents/Resources directory and I'm guessing that's not intentional.

ls -lt  /Applications/Atom.app/Contents/Resources
total 186320
-rw-r--r--  1 nick  staff    118895 Oct 14 11:18 *
-rw-r-----@ 1 nick  staff    302093 Oct 14 11:18 atom.icns
-rw-r--r--  1 nick  staff   1190875 Oct 14 10:42 atom.icns.zip
-rw-r--r--  1 nick  staff   1164803 Oct 14 10:42 electron.icns.zip
-rw-r--r--  1 nick  staff    553284 Oct 14 10:42 file.icns.zip

**Comment by danielbayley** [comment] 2016-10-16 12:07
Very strange… I can't reproduce a problem at all!

@ndobson Have you set any custom paths to icons in the package settings? Or just put an `atom.icns` in your `ATOM_HOME` folder? (`~/.atom` by default) Try restarting Atom and/or <kbd>⌘</kbd>-click Atom in the Dock… does the icon change?

@JunkMyFunk Did the update work for you?

I did also have a rogue "`*`" file in `/Applications/Atom.app/Contents/Resources`… this is obviously from a glob pattern taken literally; I think maybe it should use `null_glob` instead of disabling `no_match` to prevent this, although again I can't reproduce it.

**Comment by ndobson** [comment] 2016-10-16 16:18
No custom paths, i just put an `atom.icns` file in `~/.atom` like you said. Restarted Atom a number of times.

I sort of got it to work, I saw this in the App info which was weird. So i cleared the icon cache, restarted Finder, and then it worked.

<img width="337" alt="atom icon" src="https://cloud.githubusercontent.com/assets/870783/19418805/6d186b5c-9391-11e6-9058-4c00edb12684.png">

```
sudo find /private/var/folders/ \
  -name com.apple.dock.iconcache -exec rm {} \;

sudo find /private/var/folders/ \
  -name com.apple.iconservices -exec rm -rf {} \;

sudo rm -rf /Library/Caches/com.apple.iconservices.store
```

**Comment by danielbayley** [comment] 2016-10-16 17:03
Ah ok, so this is a wider problem with custom icons generally showing up in Finder rather than a bug with this package…

It might be good for the package to also reset the icon cache, but only if there's a non-sudo way to do it… I don't really want to be calling `rm -rf` on things.

Incidentally there's a quicker manual workaround to update the icon in Finder… Just drag a nearby app onto where the icon is in that same info window then delete it (backspace), which triggers an update. You can also <kbd>⌘</kbd>-click on Atom in the Dock like I said, which should work…

**Comment by danielbayley** [comment] 2016-10-16 17:04
Closing for now… let me know if any problems with the package _actually_ changing the icon.

**Closed as completed by danielbayley** 2016-10-16 17:04 UTC
